name: CI-CD-AWS
env:
  S3_BUCKET_NAME      : "github-test-deployment" 
  DEPLOY_PACKAGE_NAME : "project_${{ github.sha }}.zip"
  S3_REGION_NAME      : "eu-north-1"

on:
  push:
    branches:
      - master
jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: echo "test"
      
#    - name: Git clove our repo
#      uses: actions/checkout@v1
    
#    - name: Create archive
#      uses: zip -r env.github-test-deployment ./ -x ".*git*"
      
      
