name: CI-CD-AWS
env:
  S3_BUCKET_NAME      : "github-test-deployment" 
  DEPLOY_PACKAGE_NAME : "project_${{ github.sha }}.zip"
  S3_REGION_NAME      : "eu-north-1"

on:
  push:
    branches:
      - main

jobs:
  my_ci_pipeline:
    runs-on : ubuntu-latest
    
    steps:
    - name: clone content
      uses: actions/checkout@v1

    - name : list files
      run  : ls -la

    - name : prepare zip archive
      run  : |
        zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x "*.git"
        ls -la
        echo ${{ secrets.MY_AWS_ACCESS_KEY }}
        echo ${{ secrets.MY_AWS_SECRET_KEY }}

    - name : Configure AWS credentials
      uses : aws-actions/configure-aws-credentials@v1
      with :
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region           : ${{ env.S3_REGION_NAME }} 

    - name : deploy package to S3 bucket
      run  : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/

